version: '3.5'
services:
  create:
    hostname: create-service
    container_name: create-service
    build: ./services/create
    depends_on:
      - mongodb
    ports:
      - 7001:7001
    volumes:
      - .:/usr/src/application
    env_file:
      - ./services/create/.env
    networks:
      - tiered
  ui:
    hostname: frontend
    container_name: frontend
    build: ./ui
    depends_on:
      - create
    ports:
      - 9001:9001
    volumes:
      - .:/usr/src/application
    env_file:
      - ./ui/.env
    networks:
      - tiered
  mongodb:
    hostname: data-tier
    container_name: data-tier
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/usr/data/db
    command: mongod 
    networks:
      - tiered
networks:
  tiered: