version: '3.5'
services:
  create-server:
    hostname: create-service
    container_name: create-service
    build: ./services/create/server
    depends_on:
      - mongodb
    ports:
      - 7001:7001
    volumes:
      - .:/usr/src/application
    env_file:
      - ./services/create/server/.env
    networks:
      - tiered
  mongodb:
    hostname: database
    container_name: data-tier
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/usr/data/db
    command: mongod #--smallfiles --logpath=/dev/null
    networks:
      - tiered
networks:
  tiered: