// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create-service.proto

/*
Package create_service is a generated protocol buffer package.

It is generated from these files:
	create-service.proto

It has these top-level messages:
	Task
	CreateRequest
	CreateResponse
*/
package create_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Priority    int32  `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type CreateRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Task  *Task  `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CreateResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoCreateService service

type TodoCreateServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type todoCreateServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoCreateServiceClient(cc *grpc.ClientConn) TodoCreateServiceClient {
	return &todoCreateServiceClient{cc}
}

func (c *todoCreateServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/TodoCreateService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoCreateService service

type TodoCreateServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterTodoCreateServiceServer(s *grpc.Server, srv TodoCreateServiceServer) {
	s.RegisterService(&_TodoCreateService_serviceDesc, srv)
}

func _TodoCreateService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoCreateServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoCreateService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoCreateServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoCreateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TodoCreateService",
	HandlerType: (*TodoCreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TodoCreateService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "create-service.proto",
}

func init() { proto.RegisterFile("create-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x4d, 0x17, 0x9d, 0xc5, 0x8a, 0xc3, 0x1e, 0xe2, 0x9e, 0x4a, 0x4f, 0x2b, 0x62,
	0x0e, 0xeb, 0x5d, 0x04, 0xff, 0x41, 0xdc, 0x3f, 0x10, 0x9b, 0x01, 0x43, 0x31, 0x13, 0x93, 0x28,
	0xf8, 0xef, 0xc5, 0x44, 0x17, 0x8b, 0xb7, 0xcc, 0x97, 0x97, 0xf7, 0x5e, 0x06, 0x36, 0x53, 0x24,
	0x93, 0xe9, 0x36, 0x51, 0xfc, 0x70, 0x13, 0xa9, 0x10, 0x39, 0xf3, 0xf8, 0x02, 0xe2, 0x60, 0xd2,
	0x8c, 0x3d, 0xb4, 0xce, 0xca, 0x66, 0x68, 0x76, 0x67, 0xba, 0x75, 0x16, 0x11, 0x84, 0x37, 0xaf,
	0x24, 0xdb, 0x42, 0xca, 0x19, 0x07, 0x58, 0x5b, 0x4a, 0x53, 0x74, 0x21, 0x3b, 0xf6, 0xf2, 0xa4,
	0x5c, 0xfd, 0x45, 0xb8, 0x85, 0xd3, 0x10, 0x1d, 0x47, 0x97, 0x3f, 0xa5, 0x18, 0x9a, 0x5d, 0xa7,
	0x8f, 0xf3, 0xf8, 0x00, 0xe7, 0x8f, 0xa5, 0x81, 0xa6, 0xb7, 0x77, 0x4a, 0x19, 0x37, 0xd0, 0x65,
	0x9e, 0xc9, 0xff, 0xa4, 0xd6, 0x01, 0xaf, 0x40, 0x64, 0x93, 0xe6, 0x12, 0xbc, 0xde, 0x77, 0xea,
	0xbb, 0x9d, 0x2e, 0x68, 0xbc, 0x81, 0xfe, 0xd7, 0x21, 0x05, 0xf6, 0x89, 0x8e, 0xe2, 0xe6, 0x9f,
	0x78, 0x7f, 0x0f, 0x97, 0x07, 0xb6, 0x5c, 0x1f, 0x3c, 0xd5, 0x3f, 0xe3, 0x35, 0xac, 0x2a, 0xc0,
	0x5e, 0x2d, 0xca, 0x6c, 0x2f, 0xd4, 0xd2, 0xfa, 0x79, 0x55, 0xf6, 0x73, 0xf7, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x07, 0xbe, 0xe5, 0x15, 0x37, 0x01, 0x00, 0x00,
}
