// Code generated by protoc-gen-go. DO NOT EDIT.
// source: update-service.proto

/*
Package update_service is a generated protocol buffer package.

It is generated from these files:
	update-service.proto

It has these top-level messages:
	Task
	UpdateRequest
	UpdateResponse
*/
package update_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Priority    int32  `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type UpdateRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Task  *Task  `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoUpdateService service

type TodoUpdateServiceClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type todoUpdateServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoUpdateServiceClient(cc *grpc.ClientConn) TodoUpdateServiceClient {
	return &todoUpdateServiceClient{cc}
}

func (c *todoUpdateServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/TodoUpdateService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoUpdateService service

type TodoUpdateServiceServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

func RegisterTodoUpdateServiceServer(s *grpc.Server, srv TodoUpdateServiceServer) {
	s.RegisterService(&_TodoUpdateService_serviceDesc, srv)
}

func _TodoUpdateService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoUpdateServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoUpdateService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoUpdateServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoUpdateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TodoUpdateService",
	HandlerType: (*TodoUpdateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _TodoUpdateService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "update-service.proto",
}

func init() { proto.RegisterFile("update-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4f, 0x03, 0x21,
	0x10, 0x85, 0xb3, 0x2b, 0xdb, 0xe8, 0x34, 0xae, 0x71, 0xd2, 0x03, 0xf6, 0xb4, 0xd9, 0x53, 0x8d,
	0x91, 0x43, 0xbd, 0x1b, 0x7f, 0x03, 0xd6, 0x1f, 0x80, 0x65, 0x12, 0xc9, 0x46, 0x06, 0x81, 0x9a,
	0xf8, 0xef, 0x8d, 0xa0, 0x8d, 0x9b, 0xde, 0x98, 0x8f, 0xc7, 0x7b, 0x8f, 0x81, 0xd5, 0x21, 0x58,
	0x93, 0xe9, 0x3e, 0x51, 0xfc, 0x74, 0x7b, 0x52, 0x21, 0x72, 0xe6, 0xf1, 0x0d, 0xc4, 0xce, 0xa4,
	0x09, 0x7b, 0x68, 0x9d, 0x95, 0xcd, 0xd0, 0x6c, 0x2e, 0x74, 0xeb, 0x2c, 0x22, 0x08, 0x6f, 0xde,
	0x49, 0xb6, 0x85, 0x94, 0x33, 0x0e, 0xb0, 0xb4, 0x94, 0xf6, 0xd1, 0x85, 0xec, 0xd8, 0xcb, 0xb3,
	0x72, 0xf5, 0x1f, 0xe1, 0x1a, 0xce, 0x43, 0x74, 0x1c, 0x5d, 0xfe, 0x92, 0x62, 0x68, 0x36, 0x9d,
	0x3e, 0xce, 0xe3, 0x13, 0x5c, 0xbe, 0x94, 0x06, 0x9a, 0x3e, 0x0e, 0x94, 0x32, 0xae, 0xa0, 0xcb,
	0x3c, 0x91, 0xff, 0x4d, 0xad, 0x03, 0xde, 0x80, 0xc8, 0x26, 0x4d, 0x25, 0x78, 0xb9, 0xed, 0xd4,
	0x4f, 0x3b, 0x5d, 0xd0, 0x78, 0x07, 0xfd, 0x9f, 0x43, 0x0a, 0xec, 0x13, 0x1d, 0xc5, 0xcd, 0x89,
	0x78, 0xfb, 0x08, 0xd7, 0x3b, 0xb6, 0x5c, 0x1f, 0x3c, 0xd7, 0x3f, 0xe3, 0x2d, 0x2c, 0x2a, 0xc0,
	0x5e, 0xcd, 0xca, 0xac, 0xaf, 0xd4, 0xdc, 0xfa, 0x75, 0x51, 0xf6, 0xf3, 0xf0, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x50, 0xaf, 0xb9, 0x99, 0x37, 0x01, 0x00, 0x00,
}
