// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delete-service.proto

/*
Package delete_service is a generated protocol buffer package.

It is generated from these files:
	delete-service.proto

It has these top-level messages:
	Task
	DeleteRequest
	DeleteResponse
*/
package delete_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Priority    int32  `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type DeleteRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Success int64 `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteResponse) GetSuccess() int64 {
	if m != nil {
		return m.Success
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoDeleteService service

type TodoDeleteServiceClient interface {
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type todoDeleteServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoDeleteServiceClient(cc *grpc.ClientConn) TodoDeleteServiceClient {
	return &todoDeleteServiceClient{cc}
}

func (c *todoDeleteServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/TodoDeleteService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoDeleteService service

type TodoDeleteServiceServer interface {
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterTodoDeleteServiceServer(s *grpc.Server, srv TodoDeleteServiceServer) {
	s.RegisterService(&_TodoDeleteService_serviceDesc, srv)
}

func _TodoDeleteService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDeleteServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoDeleteService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDeleteServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoDeleteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TodoDeleteService",
	HandlerType: (*TodoDeleteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _TodoDeleteService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delete-service.proto",
}

func init() { proto.RegisterFile("delete-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4e, 0xc3, 0x30,
	0x0c, 0x86, 0xd5, 0xac, 0x1b, 0x60, 0x44, 0x11, 0xd6, 0x0e, 0xd1, 0x4e, 0x55, 0x4f, 0x03, 0x89,
	0x1e, 0x40, 0x5c, 0x39, 0xf1, 0x04, 0x61, 0x2f, 0x30, 0x12, 0x4b, 0x44, 0x83, 0x38, 0xc4, 0x19,
	0x12, 0x6f, 0x8f, 0x94, 0xac, 0x88, 0xde, 0xf2, 0xff, 0xf1, 0x6f, 0x7f, 0x36, 0xac, 0x1d, 0x7d,
	0x50, 0xa6, 0x7b, 0xa1, 0xf4, 0xed, 0x2d, 0x8d, 0x31, 0x71, 0xe6, 0xe1, 0x1d, 0xda, 0xdd, 0x5e,
	0x0e, 0xd8, 0x81, 0xf2, 0x4e, 0x37, 0x7d, 0xb3, 0xbd, 0x30, 0xca, 0x3b, 0x44, 0x68, 0xc3, 0xfe,
	0x93, 0xb4, 0x2a, 0x4e, 0x79, 0x63, 0x0f, 0x97, 0x8e, 0xc4, 0x26, 0x1f, 0xb3, 0xe7, 0xa0, 0x17,
	0xe5, 0xeb, 0xbf, 0x85, 0x1b, 0x38, 0x8f, 0xc9, 0x73, 0xf2, 0xf9, 0x47, 0xb7, 0x7d, 0xb3, 0x5d,
	0x9a, 0x3f, 0x3d, 0x3c, 0xc1, 0xd5, 0x4b, 0x21, 0x30, 0xf4, 0x75, 0x24, 0xc9, 0xb8, 0x86, 0x65,
	0xe6, 0x03, 0x85, 0xd3, 0xd4, 0x2a, 0x4e, 0x20, 0x6a, 0x02, 0x19, 0xee, 0xa0, 0x9b, 0x62, 0x12,
	0x39, 0x08, 0xa1, 0x86, 0x33, 0x39, 0x5a, 0x4b, 0x22, 0x25, 0xb9, 0x30, 0x93, 0x7c, 0x78, 0x86,
	0x9b, 0x1d, 0x3b, 0xae, 0xf5, 0xaf, 0x75, 0x4f, 0xbc, 0x85, 0x55, 0x35, 0xb0, 0x1b, 0x67, 0x00,
	0x9b, 0xeb, 0x71, 0xde, 0xf9, 0x6d, 0x55, 0x6e, 0xf2, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x02,
	0xea, 0x8c, 0x4d, 0x2b, 0x01, 0x00, 0x00,
}
